### PR TITLE
1st prototype

### PR DESCRIPTION
**Pull request by diarmuidclarke**
### Your checklist for this pull request

🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [x] Make sure you are making a pull request against the **canary branch** (left side). Also you should start _your branch_ off _our canary_.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.

### Description
first proto merge to main

### CODE REVIEW

**Comment by diarmuidclarke** [comment]
@pzach - Hi Piotr, this is the code from the first week of work form Derby College - I've only made some minor tweaks. 
Added requirements.txt for pip
.gitignore updated for python stuff like ignoring pycache folders

**Review by pzach — COMMENTED** [review]
approved

**Comment by diarmuidclarke** [comment]
> approved

Hi Piotr can you check if there is an approve button for your review? Looks like your review was not completed. Thanks
No rush but I happened to be looking at it just now
Thanks
Diarmuid

**Review by pzach — APPROVED** [review]
done

**Pull request closed without merging**
