### PR TITLE
update main

### PR DESCRIPTION
**Pull request by diarmuidclarke**
### Your checklist for this pull request

🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [x] Make sure you are making a pull request against the **canary branch** (left side). Also you should start _your branch_ off _our canary_.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.

### Description

Please describe your pull request.

💔Thank you!

### CODE REVIEW

**Review by baselakasha — APPROVED** [review]
Cool

**Review by baselakasha — APPROVED** [review]

**Review by diarmuidclarke — COMMENTED** [review]
this gets us from a boilerplate readme to a first draft that explains the project

**Review by baselakasha — APPROVED** [review]
I see, I had to click the little checkbox to confirm that I viewed the code, otherwise my review would not be completed/

**Comment by baselakasha** [comment]
I guess I cant review because I don't have write access and your review does not count as you are the person who made the pull request .

**Comment by diarmuidclarke** [comment]
> I see, I had to click the little checkbox to confirm that I viewed the code, otherwise my review would not be completed/

i think you might be a reviewer that does not have write access to `main` so pull request can't progress to merge - we might need to wait for Josh on this one

**Comment by diarmuidclarke** [comment]
> I guess I cant review because I don't have write access and your review does not count as you are the person who made the pull request .

exactly, oh well, 24 hrs is ok

**Review by pzach — APPROVED** [review]
I hereby declare this pull request approved

**Comment by pzach** [comment]
approved

**Pull request merged**
